### ISSUE TITLE
Pkg should have a Makefile

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/Pkg#19]
This would make it easier to package `Pkg`!

I think there should be a branch of woof-CE called `pkg` that pulls in the latest cutting edge version from this repo and installs it into the built distro. A `Makefile` would help.

`PPM` is now in 'maintenance mode' and `Pkg` IMHO is the future.

**Comment by sc0ttj** [comment]
Will look into it..

**Comment by sc0ttj** [comment]
But note, you can do `./installer.sh` and it will install Pkg into the running system (inc registering itself as an installed package, no ppm required)

**Comment by 01micko** [comment]
That will do.
