### ISSUE TITLE
Multiarch mode pkg

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/Pkg#25]
This suggestion was weird yet it has a point. Make pkg ablet to support multilib for 64-bit which means on 64-bit puppy it can install 32-bit applications. Also add a capability for side-by-side application installation for example both 64-bit and 32-bit gimp can be install side-by-side since the puppy was 64-bit just add 32-bit tag on Name field of desktop file. And it appears on menu like this

Gimp
Gimp (32-bit)

**Comment by sc0ttj** [comment]
You will need to explain exactly what needs to be done:

- this sounds like the work needed lives **outside** of Pkg ... 

Cos Pkg will install any package you tell it, to / ... If the package works or not depends on the package and system.

If the system supports multiarch stuff, then Pkg would .. 

If I am misunderstanding, please explain exactly what changes would need to go into Pkg.

For example:

```
# install 32 bit gimp in 64 bit puppy
pkg add gimp_2.37-1_i386

# run gimp
gimp

# (show errors here)
```

and some suggestions on what Pkg needs to do to make gimp work, that is currently does not do....

**Comment by sc0ttj** [comment]
Re-reading the first post, it seems all the work required is _supposed_ to go inside the packages themselves, or their dependencies.. Closing this as irrelevant.
