### ISSUE TITLE
There should be only 1 .desktop file

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/Pkg#26]
As the title says.. and it should run a script (`pkg_gui` or something) that calls either `exec`s `gpkgdialog`, `Xpkgdialog` or `pkgdialog` in that order (up for debate) and make it user configurable if the use doesn't like that order.

We all know puppy's menu is too cluttered.

**Comment by sc0ttj** [comment]
Agreed.

FYI I prefer the Pkgdialog frontend, as it can be used without X, and over ssh, etc.

But all the frontends need work..  I'm happy for others to decide which frontend is loaded from the menu.
