### ISSUE TITLE
pkg search doesn't quite find everything

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/Pkg#30]
![pkg](https://user-images.githubusercontent.com/1019119/71774582-8c74a300-2fbd-11ea-824e-9a163dd97098.png)

`vlc` exists in the slacko64 14.2 repo (second entry in above pic with `search-all`) so why isn't it shown with `pkg search vlc`? Is it supposed to? (methinks 'yes' - but could be wrong).

Hmmmm ... and this is a bug
```
# pkg add vlc
Download vlc-gtk from noarch repo:  
URL: http://ftp.nluug.nl/os/Linux/distr/puppylinux/pet_packages-noarch/vlc-gtk-2.7-noarch.pet
Downloading vlc-gtk-2.7-noarch.pet. Please wait: 100%
Downloaded: /root/pkg/vlc-gtk-2.7-noarch.pet
Install package vlc-gtk-2.7-noarch:  
Installed: vlc-gtk-2.7-noarch
Menu entry:     Multimedia -> VLC-gtk - simple VLC frontend
Resolving dependencies..
Dependencies to get: vlc_nogui xdotools 
# 
```
There seems to be no `vlc_nogui` anyway for slacko64, and perhaps not `xdotool`.

**Comment by sc0ttj** [comment]
Can you please confirm this is with the very latest Pkg ... Some recent commits fixed a regression where package name search was not returning all of its results properly..

**Comment by 01micko** [comment]
The day I reported the issue (Jan 4) is the day I cloned `Pkg` so I believe there is something not quite right with slacko regarding search.

BTW, where do you want PRs? At upstream (gitlab)? I suppose that would be the cleanest way for git history.

**Comment by sc0ttj** [comment]
Yeah Gitlab, please.

**Comment by sc0ttj** [comment]
@01micko  Just had a thought... Did you double check that your current repo was the intended slackware one, and not the `noarch` repo...  If your current repo was noarch when you ran `pkg search vlc`, then that would explain the results

**Comment by 01micko** [comment]
Ok, repo was at `noarch`, this is after first install.

Perhaps that is a bit counter intuitive. Couldn't the installer _select_ the appropriate default repo according to `/etc/DISTRO_SPECS` ?

`vlc` installed fine once I set the current default to `slacko64-14.2` (and the bash completion was nice - only had to type `pkg r slacko[tab]`)

**Comment by 01micko** [comment]
Hmmm... noticed an anomaly between slacko14.2 and slacko6414.2 in `sources-all`

```
slacko14.2|pet|Packages-puppy-slacko14.2-official|http://ftp.nluug.nl/os/Linux/distr/puppylinux/pet_packages-slacko14.2/|http://distro.ibiblio.org/puppylinux/pet_packages-slacko14.2/|||slackware14.2 slackware14.2-salix slackware14.2-extra slacko14.1 slacko14 noarch common32 
slacko64-14.2|txz|Packages-puppy-slacko6414.2-official|http://distro.ibiblio.org/puppylinux/pet_packages-slacko6414.2/|https://ftp.nluug.nl/os/Linux/distr/puppylinux/pet_packages-slacko6414.2/|||slackware64-14.2 slackware64-14.2-salix slackware64-14.2-patches slackware64-14.2-extra noarch common64
```
 Of note are the hyphen and `txz` in the 64 bit variant. Bugs if I may say so.

I'm woofing up a slacko 14.2 pup (32 bit) right now to see if it makes a difference.

**Comment by 01micko** [comment]
Nope.. `noarch` is default in slacko 32 as well.. but I found _another_ bug

The package `install-vivaldi` fails to install, and does too in `petget`. I like the Vivaldi browser (another chromium clone) and wrote the app and it installs vivaldi in x86, x86_64 and arm so one app does all my needs. However the bug is that the repo isn't set in `noarch` (same in `petget`) .. which is...
```
https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE-noarch/master
```

**Comment by sc0ttj** [comment]
@wdlkmpx  was the last one to update the `sources-all` file... I have no idea what the default slackware repo names should be .. but it looks like the fallbacks have an extra dash in there that they don't need.. 

As for not defaulting to `noarch` on installing Pkg, and instead defaulting to the `main` repo (whatever that happens to be), I'm happy to make that the default behaviour .. 

The raw github URL above you gave me gives an 400 error ..   Happy to update the `noarch` repo URL mirrors to include whatever is the latest...

**Comment by 01micko** [comment]
Actually should be 
```
https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE-noarch/master/pet_packages-noarch/
```

That still gives `400 invalid request` but if the pet package is tacked on like so
```
https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE-noarch/master/pet_packages-noarch/install-vivaldi-0.3-noarch.pet
```
you can download the package. So perhaps in `noarch` we can add the former to the 3rd repo field.

As for the default, because puplet and even official names can vary wildly, it would perhaps be best to detect the default repo based on upstream distro name (`$DISTRO_TARGETARCH`, `$DISTRO_BINARY_COMPAT` and `$DISTRO_COMPAT_VERSION`) and nutting it out with a `case` statement.

**Comment by 01micko** [comment]
I'm going to close this as the OP is somewhat solved, although the `pkg` install script could do with improvement - even put some stuff in a separate `pinstall.sh`, but that is the subject of a different issue.

**Comment by sc0ttj** [comment]
OK I tracked down the offending change .. It was me, when I added LxPup stuff ... Dunno why I also added a dash slacko6414.1 .. I might have copied them from an LxPup ... Might have to mount one and see what repos it has in there.. 

Anyway, here is the new entry I think would be right (going by your comments above):

```
slacko6414.2|pet|Packages-puppy-slacko6414.2-official|https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE-noarch/master/pet_packages-noarch/|http://distro.ibiblio.org/puppylinux/pet_packages-slacko6414.2/|https://ftp.nluug.nl/os/Linux/distr/puppylinux/pet_packages-slacko6414.2/||slackware64-14.2 slackware64-14.2-salix slackware64-14.2-patches slackware64-14.2-extra noarch common64
```

^ I've added in the new repo URL, and updated the name to remove dashes... I think it's good.. Can you confirm?? 


TBH, I prefer the name _with_ the dashes, _if_ that works ... Haven't booted a Slack pups for about 3 years at this point so I dunno..

**Comment by 01micko** [comment]
the repo at ibiblio and mirrors for slacko64 is `pet_packages-slacko6414.2` which is consistent with `DISTRO_DB_SUBNAME` in `DISTRO_SPECS`, so I think the hyphen should be omitted, but in saying that, @peabee releases his slacko variants as `spup` which is Barry's original name for slackware compatible pups. So, really it doesn't matter. Probably the important thing is the `pet` designation in the extension field.
