### ISSUE TITLE
Make Pkg support ARM

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/Pkg#8]
Not sure what needs to be done here..

Unsure of relationship between the various choices or ARM, how they're named in Debian/Ubuntu etc, and if they differ in Slackware..

Debian (I guess):

```
ARCH_LIST="i686 x86_64 arm aarch64"
```
Slackware:

```
???
```

And how do these values relates to `DBIN_ARCH` and `DSUFFIX`?

A pull request on Pkg which adds an ARM based repo to `sources-all`, and fixes finding and donwloading packages on from it, inc deps, would be a start (before running Pkg on an ARM based pup)

**Comment by sc0ttj** [comment]
@01micko sorry to be a bother, but any thoughts on this would be great.

I don't have an ARM anything, and didn't see any ARM repos in any puppy configs I know of (unless I'm being dumb.. likely).

I know you're going with apt-get, but with the requisite fixes in `list_deps()` and `find_deps()` (which I'm defo gonna do, at _some_ point), I'm sure Pkg will be fast enough for ARM too.

**Comment by 01micko** [comment]
debian has armel, armhf and arm64

raspbian (raspberry pi) has armhf only

I believe Ubuntu has an armhf branch these days (has for a while). Haven't had much to do with Ubuntu myself lately. 

Both debian and raspbian stable have superseded 'stretch' and are now at 'buster'

Slackware 14.2 has arm soft float; current is hard float (armhf). There is also an aarch64 (arm64) unofficial port. Don't bother with that for now, I'll get onto that in the new year.

If you trawl woof, you'll see more in `woof-distro`

HTH

**Comment by 01micko** [comment]
> I know you're going with apt-get

Only using that in [rasvuan](http://www.murga-linux.com/puppy/viewtopic.php?t=116529) , an experimental distro using woof-CE/zwn based on Devuan Ascii `armhf`

[Raspup](http://www.murga-linux.com/puppy/viewtopic.php?t=116841) is pure Puppy Linux warts and all; it uses Raspbian Buster libs and bins. It is certainly capable of using `Pkg`.

'baby steps' needed here. `raspup` is approaching release. RC2 will be out in days and it's very close to final. `Pkg` should initially support `armhf` for Raspian/Debian Buster then progress from there.

**Comment by sc0ttj** [comment]
Thanks for the info.. 

I'll try to do some pre-emptive fixes so making Pkg work after first ever install on an ARM pup won't be so laborious..  

Yeah I'm in no rush to "get Pkg into" anything.. But wanna make sure it works as wel las poss.

**Comment by 01micko** [comment]
`pkg` already supports arm. Just need to point to correct repo.
